version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_operations
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: crud_operations
      DB_WAITFORCONNECTIONS: "true"
      DB_CONNECTIONLIMIT: "10"
      DB_QUEUELIMIT: "0"
      DB_TABLENAME: "users"
    networks:
      - my_network

networks:
  my_network:
